drop procedure if exists "DBA"."Export_to_MySQL";

CREATE PROCEDURE "DBA"."Export_to_MySQL" () 
BEGIN
 	UNLOAD TABLE LOG_HUMIDADETEMPERATURA TO 'Z:\\VM_SHAREDFOLDER\\Log_HumidadeTemperatura.txt';
	UNLOAD TABLE LOG_VARIAVEISMEDIDAS TO 'Z:\\VM_SHAREDFOLDER\\Log_VariaveisMedidas.txt';
    UNLOAD TABLE LOG_VARIAVEIS TO 'Z:\\VM_SHAREDFOLDER\\Log_Variaveis.txt';
    UNLOAD TABLE LOG_CULTURA TO 'Z:\\VM_SHAREDFOLDER\\Log_Cultura.txt';
	UNLOAD TABLE LOG_INVESTIGADORES TO 'Z:\\VM_SHAREDFOLDER\\Log_Investigadores.txt';
    UNLOAD TABLE LOG_MEDICOES TO 'Z:\\VM_SHAREDFOLDER\\Log_Medicoes.txt';
    UNLOAD TABLE LOG_CONSULTAS TO 'Z:\\VM_SHAREDFOLDER\\Log_Consultas.txt';
END;
