INSERT INTO Investigador (email, nomeInvestigador, deleted) VALUES ('user1@sid.pt', 'Investigador 1', 0);
INSERT INTO Investigador (email, nomeInvestigador, deleted) VALUES ('user2@sid.pt', 'Investigador 2', 0);
INSERT INTO Investigador (email, nomeInvestigador, deleted) VALUES ('user3@sid.pt', 'Investigador 3', 0);
INSERT INTO Investigador (email, nomeInvestigador, deleted) VALUES ('user4@sid.pt', 'Investigador 4', 0);
INSERT INTO Investigador (email, nomeInvestigador, deleted) VALUES ('user5@sid.pt', 'Investigador 5', 0);
INSERT INTO Investigador (email, nomeInvestigador, deleted) VALUES ('user6@sid.pt', 'Investigador 6', 0);
INSERT INTO Investigador (email, nomeInvestigador, deleted) VALUES ('user7@sid.pt', 'Investigador 7', 0);
INSERT INTO Investigador (email, nomeInvestigador, deleted) VALUES ('user8@sid.pt', 'Investigador 8', 0);
INSERT INTO Investigador (email, nomeInvestigador, deleted) VALUES ('user9@sid.pt', 'Investigador 9', 0);
INSERT INTO Investigador (email, nomeInvestigador, deleted) VALUES ('user10@sid.pt', 'Investigador 10', 0);

INSERT INTO Cultura (idInvestigador, nomeCultura, limiteInferiorTemperatura, limiteSuperiorTemperatura, limiteInferiorHumidade, limiteSuperiorHumidade, deleted) VALUES (1, 'Cult1', 10, 17, 70, 80, 0);
INSERT INTO Cultura (idInvestigador, nomeCultura, limiteInferiorTemperatura, limiteSuperiorTemperatura, limiteInferiorHumidade, limiteSuperiorHumidade, deleted) VALUES (2, 'Cult2', 11, 15, 65, 75, 0);
INSERT INTO Cultura (idInvestigador, nomeCultura, limiteInferiorTemperatura, limiteSuperiorTemperatura, limiteInferiorHumidade, limiteSuperiorHumidade, deleted) VALUES (3, 'Cult3', 8, 12, 75, 85, 0);
INSERT INTO Cultura (idInvestigador, nomeCultura, limiteInferiorTemperatura, limiteSuperiorTemperatura, limiteInferiorHumidade, limiteSuperiorHumidade, deleted) VALUES (3, 'Cult4', 13, 16, 60, 75, 0);
INSERT INTO Cultura (idInvestigador, nomeCultura, limiteInferiorTemperatura, limiteSuperiorTemperatura, limiteInferiorHumidade, limiteSuperiorHumidade, deleted) VALUES (4, 'Cult5', 15, 19, 70, 80, 0);

INSERT INTO Variaveis (nomeVariavel, deleted) VALUES ('Temp1', 0);
INSERT INTO Variaveis (nomeVariavel, deleted) VALUES ('Temp2', 0);
INSERT INTO Variaveis (nomeVariavel, deleted) VALUES ('Temp3', 0);
INSERT INTO Variaveis (nomeVariavel, deleted) VALUES ('Temp4', 0);
INSERT INTO Variaveis (nomeVariavel, deleted) VALUES ('Temp5', 0);
INSERT INTO Variaveis (nomeVariavel, deleted) VALUES ('Humid1', 0);
INSERT INTO Variaveis (nomeVariavel, deleted) VALUES ('Humid2', 0);
INSERT INTO Variaveis (nomeVariavel, deleted) VALUES ('Humid3', 0);
INSERT INTO Variaveis (nomeVariavel, deleted) VALUES ('Humid4', 0);
INSERT INTO Variaveis (nomeVariavel, deleted) VALUES ('Humid5', 0);

INSERT INTO VariaveisMedidas (idCultura, idVariavel, limiteInferior, limiteSuperior, deleted) VALUES (1, 1, 15, 16, 0);
INSERT INTO VariaveisMedidas (idCultura, idVariavel, limiteInferior, limiteSuperior, deleted) VALUES (2, 2, 16, 17, 0);
INSERT INTO VariaveisMedidas (idCultura, idVariavel, limiteInferior, limiteSuperior, deleted) VALUES (1, 6, 72, 75, 0);
INSERT INTO VariaveisMedidas (idCultura, idVariavel, limiteInferior, limiteSuperior, deleted) VALUES (3, 3, 14, 15, 0);
INSERT INTO VariaveisMedidas (idCultura, idVariavel, limiteInferior, limiteSuperior, deleted) VALUES (4, 5, 13, 14, 0);
INSERT INTO VariaveisMedidas (idCultura, idVariavel, limiteInferior, limiteSuperior, deleted) VALUES (2, 7, 70, 72, 0);
INSERT INTO VariaveisMedidas (idCultura, idVariavel, limiteInferior, limiteSuperior, deleted) VALUES (5, 4, 15, 16, 0);
INSERT INTO VariaveisMedidas (idCultura, idVariavel, limiteInferior, limiteSuperior, deleted) VALUES (3, 8, 76, 78, 0);
INSERT INTO VariaveisMedidas (idCultura, idVariavel, limiteInferior, limiteSuperior, deleted) VALUES (4, 9, 74, 76, 0);
INSERT INTO VariaveisMedidas (idCultura, idVariavel, limiteInferior, limiteSuperior, deleted) VALUES (5, 10, 72, 74, 0);

INSERT INTO Medicoes (idCultura, idVariavel, dataMedicao, horaMedicao, deleted) VALUES (1, 1, '2018-03-01', '10:31', 0);
INSERT INTO Medicoes (idCultura, idVariavel, dataMedicao, horaMedicao, deleted) VALUES (2, 2, '2018-03-01', '10:32', 0);
INSERT INTO Medicoes (idCultura, idVariavel, dataMedicao, horaMedicao, deleted) VALUES (1, 6, '2018-03-01', '10:33', 0);
INSERT INTO Medicoes (idCultura, idVariavel, dataMedicao, horaMedicao, deleted) VALUES (3, 3, '2018-03-01', '10:34', 0);
INSERT INTO Medicoes (idCultura, idVariavel, dataMedicao, horaMedicao, deleted) VALUES (4, 5, '2018-03-01', '10:35', 0);
INSERT INTO Medicoes (idCultura, idVariavel, dataMedicao, horaMedicao, deleted) VALUES (2, 7, '2018-03-01', '10:36', 0);
INSERT INTO Medicoes (idCultura, idVariavel, dataMedicao, horaMedicao, deleted) VALUES (5, 4, '2018-03-01', '10:37', 0);
INSERT INTO Medicoes (idCultura, idVariavel, dataMedicao, horaMedicao, deleted) VALUES (3, 8, '2018-03-01', '10:38', 0);
INSERT INTO Medicoes (idCultura, idVariavel, dataMedicao, horaMedicao, deleted) VALUES (4, 9, '2018-03-01', '10:39', 0);
INSERT INTO Medicoes (idCultura, idVariavel, dataMedicao, horaMedicao, deleted) VALUES (5, 10, '2018-03-01', '10:40', 0);
INSERT INTO Medicoes (idCultura, idVariavel, dataMedicao, horaMedicao, deleted) VALUES (1, 1, '2018-03-02', '13:12', 0);
INSERT INTO Medicoes (idCultura, idVariavel, dataMedicao, horaMedicao, deleted) VALUES (2, 2, '2018-03-02', '13:13', 0);
INSERT INTO Medicoes (idCultura, idVariavel, dataMedicao, horaMedicao, deleted) VALUES (1, 6, '2018-03-02', '13:14', 0);
INSERT INTO Medicoes (idCultura, idVariavel, dataMedicao, horaMedicao, deleted) VALUES (3, 3, '2018-03-02', '13:15', 0);
INSERT INTO Medicoes (idCultura, idVariavel, dataMedicao, horaMedicao, deleted) VALUES (4, 5, '2018-03-02', '13:16', 0);
INSERT INTO Medicoes (idCultura, idVariavel, dataMedicao, horaMedicao, deleted) VALUES (2, 7, '2018-03-02', '13:17', 0);
INSERT INTO Medicoes (idCultura, idVariavel, dataMedicao, horaMedicao, deleted) VALUES (5, 4, '2018-03-02', '13:18', 0);
INSERT INTO Medicoes (idCultura, idVariavel, dataMedicao, horaMedicao, deleted) VALUES (3, 8, '2018-03-02', '13:19', 0);
INSERT INTO Medicoes (idCultura, idVariavel, dataMedicao, horaMedicao, deleted) VALUES (4, 9, '2018-03-02', '13:20', 0);
INSERT INTO Medicoes (idCultura, idVariavel, dataMedicao, horaMedicao, deleted) VALUES (5, 10, '2018-03-02', '13:21', 0);
